name: Email Engine Worker

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-email-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: email-engine
        run: npm install

      - name: Run worker
        working-directory: email-engine
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}

          PAYPAL_ENVIRONMENT: ${{ secrets.PAYPAL_ENVIRONMENT }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
          PAYPAL_WEBHOOK_ID: ${{ secrets.PAYPAL_WEBHOOK_ID }}

          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_IMAP_HOST: ${{ secrets.EMAIL_IMAP_HOST }}
          EMAIL_IMAP_PORT: ${{ secrets.EMAIL_IMAP_PORT }}
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}

          CRON_SECRET: ${{ secrets.CRON_SECRET }}

        run: npm start
